name: post_syd_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.5
  simple_barcode_scanner: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
